name: Docker Build Only

on:
  schedule:
    - cron: '00 1 * * *'  # 每天北京时间上午9点
  workflow_dispatch:

env:
  IMAGE_NAME: woshi17/docker-drpy-node

jobs:
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1

  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag: latest-amd64
          - platform: linux/arm64
            tag: latest-arm64
          - platform: linux/arm/v7
            tag: latest-armv7

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile2
          platforms: ${{ matrix.platform }}
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.tag }}

      - name: Save Docker image as artifact
        run: |
          docker save -o image-${{ matrix.tag }}.tar \
            ${{ env.IMAGE_NAME }}:${{ matrix.tag }}

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.tag }}
          path: image-${{ matrix.tag }}.tar
