name: build-docker

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  REGISTRY: docker.io
  IMAGE_NAME: woshi17/drpy-node   # Docker Hub 仓库

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 QEMU（支持多架构构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 3️⃣ 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 5️⃣ 提取 package.json 的 version
      - name: Extract version from package.json
        id: pkg
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # 6️⃣ 生成 Docker metadata（tags 和 labels）
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.pkg.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}

      # 7️⃣ 构建并推送镜像
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

