name: Docker Publish

on:
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: woshi17/docker-drpy-node

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag: latest-amd64
            arch: amd64
          - platform: linux/arm64
            tag: latest-arm64
            arch: arm64
          - platform: linux/arm/v7
            tag: latest-armv7
            arch: armv7
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            TARGETARCH=${{ matrix.arch }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}

  combine-images:
    runs-on: ubuntu-latest
    needs: build-matrix
    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Create and push manifest list
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-amd64,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-armv7
          push: true
